---
namespace: "haidra"
name: "deployments"
version: "0.3.1"
readme: "README.md"
authors:
  - Divided by Zer0 <mail@dbzer0.com>
dependencies:
  "prometheus.prometheus": ">=0.16.0,<1.0.0"
  "grafana.grafana": ">=6.0.0,<7.0.0"
license:
  - "AGPL-3.0-or-later"
tags:
  - haidra
  - aihorde
repository: "https://github.com/Haidra-Org/deployments"
issues: "https://github.com/Haidra-Org/deployments/issues"
description: Ansible collection for Haidra deployments
