---
galaxy_info:
  role_name: amd_gpu_drivers
  author: Haidra-Org
  description: Setup AMD GPU drivers and ROCm on Ubuntu 22.04 (Jammy) hosts
  license: AGPL-3.0-or-later
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
  galaxy_tags:
    - amd
    - gpu
    - rocm
    - horde
dependencies: []
