---
- name: Install dependencies
  ansible.builtin.package:
    state: present
    name:
      - certbot
      - haproxy
      - python3-cryptography
  tags:
    - haproxy
    - packages

- name: Ensure haproxy config directory exists
  ansible.builtin.file:
    path: /etc/haproxy/cert
    owner: root
    group: root
    state: directory
    mode: "0755"
  tags:
    - haproxy

- name: Generate an OpenSSL private key with the default values (4096 bits, RSA)
  community.crypto.openssl_privatekey:
    path: /etc/haproxy/cert/{{ artbot_revproxy_domain }}.key
  when: artbot_revproxy_self_signed_cert
  tags:
    - haproxy

- name: Generate a Self Signed OpenSSL certificate
  community.crypto.x509_certificate:
    path: /etc/haproxy/cert/{{ artbot_revproxy_domain }}.crt
    privatekey_path: /etc/haproxy/cert/{{ artbot_revproxy_domain }}.key
    provider: selfsigned
  when: artbot_revproxy_self_signed_cert
  tags:
    - haproxy

- name: Create merged certificate
  ansible.builtin.assemble:
    src: /etc/haproxy/cert
    dest: /etc/haproxy/cert/{{ artbot_revproxy_domain }}.pem
    regexp: "{{ artbot_revproxy_domain }}\\.(key|crt)$"
    owner: root
    group: root
    mode: "0600"
  when: artbot_revproxy_self_signed_cert
  tags:
    - haproxy

- name: Ensure certbot is configured for the domain {{ artbot_revproxy_domain }}
  ansible.builtin.command: >
    certbot certonly
    --domains {{ artbot_revproxy_domain }},{{ artbot_revproxy_other_domains }}
    --keep-until-expiring --agree-tos --standalone
    --http-01-port 60001 --email {{ artbot_revproxy_email }}
    --standalone -n --expand
  register: artbot_revproxy__certbot_result
  changed_when: "'no action taken' not in artbot_revproxy__certbot_result.stdout"
  tags:
    - cert
    - haproxy
  when: not artbot_revproxy_self_signed_cert

- name: Merge certbot certificates for {{ artbot_revproxy_domain }}
  ansible.builtin.assemble:
    src: /etc/letsencrypt/live/{{ artbot_revproxy_domain }}
    dest: /etc/haproxy/cert/{{ artbot_revproxy_domain }}.pem
    regexp: '(privkey|fullchain)\.pem$'
    owner: root
    group: root
    mode: "0600"
  when: not artbot_revproxy_self_signed_cert
  tags:
    - cert
    - haproxy

- name: Ensure Haproxy Configuration
  ansible.builtin.template:
    src: "{{ artbot_revproxy_haproxy_cfg_template }}"
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: "0644"
    validate: /usr/sbin/haproxy -f %s -c
  notify: Reload haproxy
  tags:
    - haproxy

- name: Ensure certificate renew script exists
  ansible.builtin.template:
    src: certbot_renew.sh.j2
    dest: /usr/local/sbin/certbot_renew.sh
    owner: root
    group: root
    mode: "0744"
  tags: haproxy

- name: Add certificate renewal on cron
  ansible.builtin.cron:
    user: root
    name: Renew Horde Certificate
    special_time: daily
    job: /usr/local/sbin/certbot_renew.sh
  tags:
    - haproxy
    - cron
