---
galaxy_info:
  role_name: horde_monitoring
  author: Haidra-Org
  description: Deploy Grafana Mimir and Grafana monitoring stack for AI Horde
  license: AGPL-3.0
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: Debian
      versions:
        - bullseye
        - bookworm
  galaxy_tags:
    - monitoring
    - grafana
    - mimir
    - docker
    - horde

dependencies: []
