---
roles:
  - geerlingguy.swap

collections:
  - name: prometheus.prometheus
    version: ">=0.16.0,<1.0.0"
  - name: grafana.grafana
    version: ">=6.0.0,<7.0.0"
  - git+https://github.com/Haidra-Org/deployments
