---
- name: Install dependencies
  ansible.builtin.apt:
    state: present
    update_cache: true
    pkg:
      - git
      - libjemalloc2
  tags:
    - packages
    - worker

- name: Ensure worker user exists ({{ worker_username }})
  ansible.builtin.user:
    name: "{{ worker_username }}"
    shell: /bin/bash
    groups:
      - video
      - render
    append: true
  tags: worker

- name: Clone Horde github repository
  ansible.builtin.git:
    repo: "{{ regen_worker_repo }}"
    dest: /home/{{ worker_username }}/{{ worker_clone_dir }}
    clone: true
    update: true
    version: "{{ regen_worker_repo_version }}"
  notify: Restart AI Worker service
  tags: worker

- name: Ensure git repo is owned by worker user ({{ worker_username }})
  ansible.builtin.file:
    path: /home/{{ worker_username }}/{{ worker_clone_dir }}
    owner: "{{ worker_username }}"
    group: "{{ worker_username }}"
    recurse: true
  tags: worker

- name: Ensure worker_runtime_dir exists ({{ worker_runtime_dir }})
  ansible.builtin.file:
    path: /home/{{ worker_username }}/{{ worker_runtime_dir }}
    owner: "{{ worker_username }}"
    group: "{{ worker_username }}"
    state: directory
    mode: "0755"
  tags:
    - worker

- name: Ensure models_dir exists ({{ models_dir }})
  ansible.builtin.file:
    path: /home/{{ worker_username }}/{{ models_dir }}
    owner: "{{ worker_username }}"
    group: "{{ worker_username }}"
    state: directory
    mode: "0755"
  tags:
    - worker

- name: Deploy bridgeData
  ansible.builtin.template:
    src: bridgeData.yaml.j2
    dest: /home/{{ worker_username }}/{{ worker_runtime_dir }}/bridgeData.yaml
    owner: "{{ worker_username }}"
    group: "{{ worker_username }}"
    mode: "0640"
  no_log: true
  notify: Restart AI Worker service
  tags:
    - worker

- name: Ensure update-runtime is run for AMD GPUs
  ansible.builtin.shell: /home/{{ worker_username }}/{{ worker_clone_dir }}/update-runtime-rocm.sh
  become: true
  become_user: "{{ worker_username }}"
  changed_when: true
  args:
    executable: /bin/bash
    chdir: /home/{{ worker_username }}/{{ worker_clone_dir }}
  register: update_runtime
  when:
    - initialize is true
    - amd_gpu is true
  tags:
    - worker
    - initialize

- name: Show update_runtime output
  ansible.builtin.debug:
    var: update_runtime
  when:
    - initialize is true
  tags:
    - worker
    - initialize
    - debug

- name: Ensure update-runtime is run for Nvidia GPUs
  ansible.builtin.shell: /home/{{ worker_username }}/{{ worker_clone_dir }}/update-runtime.sh
  become: true
  become_user: "{{ worker_username }}"
  changed_when: true
  args:
    executable: /bin/bash
    chdir: /home/{{ worker_username }}/{{ worker_clone_dir }}
  register: update_runtime
  when:
    - initialize is true
    - amd_gpu is false
  tags:
    - worker
    - initialize

- name: Show update_runtime output
  ansible.builtin.debug:
    var: update_runtime
  when:
    - initialize is true
  tags:
    - worker
    - initialize
    - debug

- name: Ensure models are downloaded for the first time
  ansible.builtin.shell:
    /home/{{ worker_username }}/{{ worker_clone_dir }}/runtime-rocm.sh python -s /home/{{ worker_username }}/{{ worker_clone_dir
    }}/download_models.py
  become: true
  become_user: "{{ worker_username }}"
  changed_when: true
  args:
    executable: /bin/bash
    chdir: /home/{{ worker_username }}/{{ worker_runtime_dir }}
  when:
    - initialize is true
    - amd_gpu is true
  tags:
    - worker
    - initialize

- name: Ensure models are downloaded for the first time
  ansible.builtin.shell:
    /home/{{ worker_username }}/{{ worker_clone_dir }}/runtime.sh python -s /home/{{ worker_username }}/{{ worker_clone_dir
    }}/download_models.py
  become: true
  become_user: "{{ worker_username }}"
  changed_when: true
  args:
    executable: /bin/bash
    chdir: /home/{{ worker_username }}/{{ worker_runtime_dir }}
  when:
    - initialize is true
    - amd_gpu is false
  tags:
    - worker
    - initialize

- name: Ensure systemd directory exists
  ansible.builtin.file:
    path: /home/{{ worker_username }}/.config/systemd/user/
    owner: "{{ worker_username }}"
    group: "{{ worker_username }}"
    mode: "0755"
    state: directory
  tags:
    - worker
    - systemd

- name: Ensure horde systemd services exist in userspace
  ansible.builtin.template:
    src: ai_horde_worker.j2
    dest: /home/{{ worker_username }}/.config/systemd/user/{{ worker_service_name }}.service
    owner: "{{ worker_username }}"
    group: "{{ worker_username }}"
    mode: "0644"
  notify: Restart AI Worker service
  tags:
    - worker
    - systemd

- name: Ensure XDG_RUNTIME_DIR is set in user's .bashrc
  ansible.builtin.lineinfile:
    path: /home/{{ worker_username }}/.bashrc
    line: export XDG_RUNTIME_DIR=/run/user/$(id -u)
    owner: "{{ worker_username }}"
    group: "{{ worker_username }}"
  tags:
    - worker
    - systemd

- name: Enable lingering if needed ({{ worker_username }})
  ansible.builtin.command: loginctl enable-linger {{ worker_username }}
  args:
    creates: /var/lib/systemd/linger/{{ worker_username }}
  tags:
    - worker
    - systemd

# Needed for the next task
- name: Find worker uid ({{ worker_username }})
  ansible.builtin.getent:
    database: passwd
  tags:
    - worker
    - systemd

- name: Ensure AI Worker service is started
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    name: "{{ worker_service_name }}"
    enabled: true
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ getent_passwd[worker_username].1 }}"
  become: true
  become_user: "{{ worker_username }}"
  register: service_started
  tags:
    - worker
    - systemd
