---

- name: Using {{ target_pkg_module.split('.')[-1] }}
  ansible.builtin.include_tasks: "install_{{ target_pkg_module.split('.')[-1] }}.yml"

- name: Ensure user is in the right groups ({{ ansible_user }})
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups:
      - video
      - render
    append: true
  tags: rocm

- name: Force all notified handlers to run at this point.
  ansible.builtin.meta: flush_handlers
  tags:
    - rocm

- name: Ensure ROCm Libraries exist in Loader Path
  ansible.builtin.lineinfile:
    dest: /etc/ld.so.conf.d/rocm.conf
    line: "{{ item }}"
    create: true
    mode: "0644"
  loop:
    - /opt/rocm/lib
    - /opt/rocm/lib64
  notify: Run ldconfig
  tags:
    - rocm

- name: Install amdgpu-fan python package
  ansible.builtin.pip:
    name: amdgpu-fan
  tags:
    - packages
    - amdfan

- name: Ensure /etc/amdgpu-fan.yml exists
  ansible.builtin.file:
    path: /etc/amdgpu-fan.yml
    state: touch
    mode: "0644"
  tags:
    - amdfan

- name: Ensure amdfan-gpu is configured
  ansible.builtin.copy:
    src: amdgpu-fan.service.ini
    dest: /etc/systemd/system/amdgpu-fan.service
    mode: "0644"
  tags:
    - amdfan

- name: Ensure amdgpu-fan service is started
  ansible.builtin.systemd:
    state: started
    daemon_reload: true
    name: amdgpu-fan
    enabled: true
  tags:
    - amdfan
    - systemd
