---
# Handlers for horde_alloy role

- name: Restart alloy
  ansible.builtin.systemd:
    name: alloy
    state: restarted
    daemon_reload: true
  become: true
  when: horde_alloy_start_service | bool

- name: Reload alloy
  ansible.builtin.systemd:
    name: alloy
    state: reloaded
  become: true
  when: horde_alloy_start_service | bool
