---
galaxy_info:
  role_name: artbot
  author: Haidra-Org
  description: Deploy Artbot web frontend for AI Horde
  license: AGPL-3.0-or-later
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: Debian
      versions:
        - bookworm
  galaxy_tags:
    - horde
    - artbot
    - nodejs
    - pm2
dependencies: []
