---
# Handlers for horde_stats_exporter role

- name: reload systemd
  systemd:
    daemon_reload: yes
  become: true

- name: restart horde-exporter
  systemd:
    name: horde-exporter
    state: restarted
  become: true
